name: Run Tests On Push
on:
  [workflow_dispatch]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.11.1
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.1
#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt
#           echo requirements installed
      - name: Run tests
        run: |
          cd tests
          pip install pytest
          pip install pytest-cov
          pytest tests.py > ../etc/out/test.out
          cd ../src/
          python data.py -h -g > ../etc/out/data.out